# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm1_joint
    - arm2_joint
    - arm3_joint
    - arm4_joint
    - arm5r_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_robot_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm1_joint
    - arm2_joint
    - arm3_joint
    - arm4_joint
  gains:
    arm1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1